name: Auto Commit

on:
  schedule:
    - cron: '0 17 * * *' # ✅ Runs at 10:30 PM IST (5:00 PM UTC)
  workflow_dispatch:  # ✅ Allows manual trigger
  
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Make changes
        run: echo "Auto commit on $(date +'%Y-%m-%d %H:%M:%S')" >> daily_update.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Automated commit on $(date)" || exit 0
          git push https://x-access-token:${{ secrets.AUTOMATION_TOKEN }}@github.com/poushalic34/auto_commit.git HEAD:main
